services:
  - type: web
    name: pepo-screener
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: BYBIT_API_KEY
        value: "10TSpdK1sHGhhPXkKs"
      - key: BYBIT_API_SECRET
        value: "OXpQhZQPGY19EBl3s9QFISiKbPZZio5UVe6m"

